# in this playbook we have declared variables everywhere, and we want check that from where ansible will take the variable values
- name: variable preference
  hosts: localhost
  vars:
    WISHES: "Morning from PLAYBOOK variable"
  # vars_files:
  #   - vars.yaml # variables declared in the vars.yaml
  vars_prompt:
    - name: WISHES
      prompt: "please enter WISHES"
      private: false
  tasks:
    - name: check preference
      # vars:
      #   WISHES: "Morning from TASK variable"
      ansible.builtin.debug:
        msg: "Hello, Good {{WISHES}}"


# 1st preference goes to arguments:
# 2nd preference goes to task level arguments:
# 3rd preference goes to variable files
#