- name: conditions
  hosts: localhost
  become: yes
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expense
    register: USER # register is a ansible variable in this we are storing the output of previously runned command id expense
    ignore_errors: true
    # output will show as rc=0 when above cmd runned successfully, rc =1 in output when the command failed
  - name: print user information
    ansible.builtin.debug:
      msg: "User info: {{USER}}"
  - name: create user
    ansible.builtin.command: useradd expense
    when: USER.rc != 0 #condition

  - name: say Hello
    ansible.builtin.debug:
      msg: "Hello"
