# number of playbook for each filters

- name: setting default value
  hosts: localhost
  tasks:
    - name: printing default value
      ansible.builtin.debug:
        msg: "hello {{ course | default('Ansible') }}"

- name: upper case
  hosts: localhost
  vars:
    greeting: "Hello, Good Morning "
  tasks:
    - name: convert into upper case
      ansible.builtin.debug:
        msg: "{{ greeting | upper }}"

- name: lower case
  hosts: localhost
  vars:
    greeting: "Hello, Good Evening "
  tasks:
    - name: convert into lower case
      ansible.builtin.debug:
        msg: "{{ greeting | lower }}"

- name: removing duplicates
  hosts: localhost
  vars:
    numbers: [1, 2, 2, 3, 8, 3, 4, 5]
  tasks:
    - name: remove duplicates
      ansible.builtin.debug:
        msg: "{{ numbers | unique }}"

- name: print min and max values
  hosts: localhost
  vars:
    age: [26, 86, 35, 2, 29, 36]
  tasks:
    - name: print min and max values
      ansible.builtin.debug:
        msg: "min age: {{ age | min }}, max age: {{ age | max }}"

- name: convert dictionary into items/list
  hosts: localhost
  vars:
    my_dict:
      course: Devops
      duration: 3-months
      trainer: sivakumar
      location: India
  tasks:
  - name: before conversion
    ansible.builtin.debug: 
      msg: "Before conversion: {{ my_dict }}"
  - name: after conversion
    ansible.builtin.debug:
      msg: "After conversion: {{ my_dict | dict2items }}"


- name: convert list/items to dictionary        # dictionary=map=key/value
  hosts: localhost
  vars:
    my_list:
      - {'key': 'course', 'value': 'Ansible'}
      - {'key': 'duration', 'value': '3-months'}
      - {'key': 'trainer', 'value': 'sivakumar'}
      - {'key': 'location', 'value': 'India'} 
  tasks:
  - name: before conversion
    ansible.builtin.debug:
      msg: "before conversion {{ my_list }} "
  - name: after conversion
    ansible.builtin.debug:
      msg: "after conversion {{ my_list | items2dict }}"