- name: demo on loops
  hosts: localhost
  tasks:
  - name: print names
    ansible.builtin.debug:        
      msg: "Hello {{item}}" # {{item }} is a reserved key word to print loops in ansible
    loop:
      - linux
      - ansible
      - docker
      - terraform
      - kubernetes
