- name: installing package using loops
  hosts: localhost
  become: true
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: latest
    loops:
    - mysql
    - nginx
    - postfix
    