- name: installing package using loop
  hosts: localhost
  become: true
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: latest
    loop:             # Ansible offers the loop, keyword to execute a task multiple times.
    - mysql
    - nginx
    - postfix
    