- name: installing package using loops
  hosts: localhost
  become: true
  tasks:
  - name: installing and removing packages
    ansible.builtin.dnf:
      name: "{{item.name}}"                 # {{item }} is a reserved key word to print loops in ansible
      state: "{{item.state}}"
    loop:                                          # Ansible offers the loop, keyword to execute a task multiple times.
    - { name: 'mysql', state: 'latest'} # item
    - { name: 'git', state: 'absent' }
    - { name: 'docker', state: 'latest' }
    