- name: installing package using loops
  hosts: localhost
  become: true
  tasks:
  - name: install packages
    ansible:builtin.debug:
      name: {{item}}
      state: latest
    loops:
    - name: installing and removing packages
      ansible:builtin.debug:
        name: {{item.name}}
        state: {{item.state}}
      loops:
      - { name: 'mysql', state: 'install'} # item
      - { name: 'git', state: 'absent' }
      - { name: 'docker', state: 'latest' }
    